version: '3.9'
services:
  recipes-database:
    image: mongo
    ports:
      - '27017:27017'
  recipe-backend:
    build: backend/
    environment:
      - PORT=3001
      - DATABASE_URL=mongodb://recipes-database:27017/recipes
    ports:
      - '3001:3001'
    depends_on:
      - recipes-database
  recipe-frontend:
    build:
      context: .
      args:
        VITE_BACKEND_URL: https://humble-space-happiness-jjjp4jgwvgjxfqg46-3001.app.github.dev/api/v1
    ports:
      - '3000:80'
    depends_on:
      - recipe-backend
